# Generated by Django 3.2.8 on 2022-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurfDetails',
            fields=[
                ('Turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('Turf_area', models.CharField(max_length=200)),
                ('Turf_name', models.CharField(max_length=200)),
            ],
        ),
    ]
