# Generated by Django 3.2.8 on 2022-05-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfdetails',
            name='Turf_catogary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
