# Generated by Django 3.2.8 on 2022-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_turfdetails_turf_catogary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Confirmation',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(max_length=200)),
                ('Turf_id', models.CharField(max_length=200)),
                ('Turf_name', models.CharField(max_length=200)),
                ('Turf_area', models.CharField(max_length=200)),
                ('Turf_catogary', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
