# Generated by Django 3.2.14 on 2023-01-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfdetails',
            name='Turf_Image',
            field=models.FileField(default=0, upload_to='Truf_Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='Turf_price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='Turf_catogary',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('FootBall', 'FootBall'), ('Badminton', 'Badminton')], max_length=200),
        ),
    ]
