# Generated by Django 3.2.14 on 2023-01-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230128_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSlot', models.CharField(choices=[('01-02 AM', '01-02 AM'), ('02-03 AM', '02-03 AM'), ('03-04 AM', '03-04 AM'), ('04-05 AM', '04-05 AM'), ('05-06 AM', '05-06 AM'), ('06-07 AM', '06-07 AM'), ('07-08 AM', '07-08 AM'), ('08-09 AM', '08-09 AM'), ('09-10 AM', '10-11 AM'), ('11-12 AM', '12-01 PM'), ('01-02 PM', '02-03 PM'), ('03-04 PM', '04-05 PM'), ('05-06 PM', '06-07 PM'), ('07-08 PM', '08-09 PM'), ('09-10 PM', '10-11 PM'), ('11-12 PM', '11-12 PM')], max_length=255)),
                ('Date', models.DateField()),
                ('Booking_status', models.BooleanField(default=FloatingPointError)),
                ('Turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.turfdetails')),
            ],
        ),
    ]
