# Generated by Django 3.2.14 on 2023-01-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='Booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
