# Generated by Django 3.2.14 on 2023-01-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_timeslot_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_confirmation',
            name='Turf_area',
        ),
        migrations.RemoveField(
            model_name='booking_confirmation',
            name='Turf_catogary',
        ),
        migrations.RemoveField(
            model_name='booking_confirmation',
            name='Turf_id',
        ),
        migrations.RemoveField(
            model_name='booking_confirmation',
            name='Turf_name',
        ),
        migrations.RemoveField(
            model_name='booking_confirmation',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking_confirmation',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking_confirmation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_confirmation',
            name='paymet_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_confirmation',
            name='slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_confirmation',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
