# Generated by Django 5.0.2 on 2024-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_confirmation_cutomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_text', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='blog_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
